### PR TITLE
Various refactors

### PR DESCRIPTION
**Pull request by techgaun**
This PR does not do much but adds couple of refactors on Dockerfiles and the install_cluster.sh

### CODE REVIEW

**Comment by blijblijblij** [comment]
Might I suggest 

http://ufpr.dl.sourceforge.net/project/pentaho/Business%20Intelligence%20Server/${BISERVER_TAG}/biserver-ce-${BISERVER_TAG}.zip -O /tmp/biserver-ce-${BISERVER_TAG}.zip

**Comment by techgaun** [comment]
@blijblijblij If you visit http://ufpr.dl.sourceforge.net/project/pentaho/Business%20Intelligence%20Server/, you will know that it won't work.

**Comment by blijblijblij** [comment]
@techgaun sorry, You are right, I use this sf url where this might make sense http://sourceforge.net/projects/pentaho/files/Business%20Intelligence%20Server/5.2/biserver-ce-5.2.0.0-209.zip/download

**Comment by wmarinho** [comment]
@techgaun, thank you very much!!

**Comment by techgaun** [comment]
@wmarinho You're welcome. And, thanks for merging the PR :+1:

**Pull request merged**
